- name: Launch httpd proxy container
  community.docker.docker_container:
    name: httpd
    image: issonotakashii/tp-devops-httpd:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    recreate: true
    restart: true
    ports:
      - "80:80"
    networks:
      - name: proxy-network
