- name: Create app docker network
  community.docker.docker_network:
    name: app-network
    state: present
- name: Create app docker network
  community.docker.docker_network:
    name: proxy-network
    state: present
