- name: Launch backend API container
  community.docker.docker_container:
    name: backend
    image: discover-docker-backend:latest
    state: started
    restart_policy: on-failure
    restart_retries: 3
    recreate: true
    restart: true
    env:
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"
      SERVER_PORT: "{{ server_port }}"
      SPRING_APPLICATION_NAME: "{{ spring_application_name }}"
    networks:
      - name: app-network
      - name: proxy-network
