- name: Stop and remove existing backend container
  community.docker.docker_container:
    name: backend
    state: absent

- name: Launch backend API container
  community.docker.docker_container:
    name: backend
    image: discover-docker-backend:latest
    pull: false
    state: started
    restart_policy: on-failure
    restart_retries: 3
    env:
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_NAME: "{{ postgres_db }}"
      DB_USERNAME: "{{ postgres_user }}"
      DB_PASSWORD: "{{ postgres_password }}"
      SERVER_PORT: "{{ server_port }}"
      SPRING_APPLICATION_NAME: "{{ spring_application_name }}"
    networks:
      - name: app-network
      - name: proxy-network
