spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:my-database}:${DB_PORT:5432}/${DB_NAME:db}
    username: ${DB_USERNAME:usr}
    password: ${DB_PASSWORD:pwd}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8080}
