name: Deploy to Development

on:
  push:
    branches: ["develop"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H sami.semlali.takima.cloud >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Deploy to development
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --vault-password-file vault_pass.txt --extra-vars "environment=development"
          rm vault_pass.txt

      - name: Quick health check
        run: |
          sleep 20
          curl -f http://sami.semlali.takima.cloud:8080/students || echo "Health check failed but continuing..."
