name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H sami.semlali.takima.cloud >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Verify Ansible files
        run: |
          ls -la ansible/
          ls -la ansible/inventories/
          ls -la ansible/playbook.yml

      - name: Deploy with Ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml --vault-password-file vault_pass.txt
          rm vault_pass.txt

      - name: Verify deployment
        run: |
          echo "Waiting for services to start..."
          sleep 45  # give more time for containers to warm up
          curl -fsS --retry 5 --retry-delay 3 http://sami.semlali.takima.cloud/students || exit 1
          echo "Deployment successful! API is responding."
