name: Test Deploy Workflow

on:
  push:
    branches: ["main"]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test deployment workflow
        run: |
          echo "🚀 Test deployment workflow is working!"
          echo "This proves the workflow file is valid"
          echo "Current branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
